spring:
  dotenv:
    enabled: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
      enabled: true
  application:
    name: codinviec
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER}
    consumer:
      group-id: email-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
server:
  port: ${SERVER_PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: ${JWT_ACCESS_EXPIRED} #15m
    refresh: ${JWT_REFRESH_EXPIRED} #7d

upload:
  image: ${UPLOAD_IMAGE}
  link:  ${UPLOAD_LINK}

client:
  url: ${CLIENT_URL}

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

vnpay:
  tmn-code: ${VNP_TMNCODE}
  hash-secret: ${VNP_HASHSECRET}
  pay-url: ${VNP_URL}
  return-url: ${VNP_RETURN_URL}
  ipn-url: ${VNP_IPN_URL}
