USE codinviec_db;

-- Role
INSERT INTO role (id, role_name, description)
VALUES ('550e8400-e29b-41d4-a716-446655440001', 'ADMIN', 'Quản trị viên hệ thống'),
       ('550e8400-e29b-41d4-a716-446655440002', 'HR', 'Nhà tuyển dụng'),
       ('550e8400-e29b-41d4-a716-446655440003', 'USER', 'Người dùng');

-- Company Size
INSERT INTO company_size (min_employees, max_employees)
VALUES (1, 10),
       (11, 50),
       (51, 200),
       (201, 500),
       (501, 1000),
       (1001, 5000),
       (5001, 10000),
       (10001, 999999);

-- Industry
INSERT INTO industry (name)
VALUES ('Công nghệ thông tin'),
       ('Phần mềm'),
       ('Thương mại điện tử'),
       ('Tài chính - Ngân hàng'),
       ('Viễn thông'),
       ('Game'),
       ('Blockchain'),
       ('AI/Machine Learning'),
       ('Cloud Computing'),
       ('Cybersecurity'),
       ('Mobile App Development'),
       ('Web Development'),
       ('Data Science'),
       ('DevOps'),
       ('UI/UX Design');

-- Job Level
INSERT INTO job_level (name)
VALUES ('Intern'),
       ('Fresher'),
       ('Junior'),
       ('Middle'),
       ('Senior'),
       ('Lead'),
       ('Manager'),
       ('Director'),
       ('VP'),
       ('C-Level');

-- Degree Level
INSERT INTO degree_level (name)
VALUES ('Không yêu cầu'),
       ('Trung cấp'),
       ('Cao đẳng'),
       ('Đại học'),
       ('Thạc sĩ'),
       ('Tiến sĩ');

-- Employment Type
INSERT INTO employment_type (name)
VALUES ('Full-time'),
       ('Part-time'),
       ('Contract'),
       ('Freelance'),
       ('Internship'),
       ('Remote'),
       ('Hybrid');

-- Experience
INSERT INTO experience (name)
VALUES ('Chưa có kinh nghiệm'),
       ('Dưới 1 năm'),
       ('1-2 năm'),
       ('2-3 năm'),
       ('3-5 năm'),
       ('5-7 năm'),
       ('7-10 năm'),
       ('Trên 10 năm');

-- Language
INSERT INTO language (name)
VALUES ('Tiếng Việt'),
       ('Tiếng Anh'),
       ('Tiếng Nhật'),
       ('Tiếng Hàn'),
       ('Tiếng Trung'),
       ('Tiếng Pháp'),
       ('Tiếng Đức'),
       ('Tiếng Tây Ban Nha');

-- Level Language
INSERT INTO level_language (name)
VALUES ('Cơ bản'),
       ('Trung bình'),
       ('Khá'),
       ('Tốt'),
       ('Thành thạo'),
       ('Bản ngữ');

-- Available Skills
INSERT INTO available_skills (name)
VALUES ('Java'),
       ('Python'),
       ('JavaScript'),
       ('TypeScript'),
       ('C++'),
       ('C#'),
       ('PHP'),
       ('Ruby'),
       ('Go'),
       ('Rust'),
       ('Swift'),
       ('Kotlin'),
       ('React'),
       ('Angular'),
       ('Vue.js'),
       ('Node.js'),
       ('Spring Boot'),
       ('Django'),
       ('Laravel'),
       ('Flutter'),
       ('React Native'),
       ('MySQL'),
       ('PostgreSQL'),
       ('MongoDB'),
       ('Redis'),
       ('Docker'),
       ('Kubernetes'),
       ('AWS'),
       ('Azure'),
       ('Git'),
       ('Linux'),
       ('Agile'),
       ('Scrum');

-- Group Core Skill
INSERT INTO group_core_skill (name)
VALUES ('Backend Development'),
       ('Frontend Development'),
       ('Full-stack Development'),
       ('Mobile Development'),
       ('DevOps'),
       ('Data Science'),
       ('Machine Learning'),
       ('Cloud Architecture'),
       ('Security'),
       ('UI/UX Design'),
       ('QA/Testing'),
       ('Project Management');

-- Category
INSERT INTO category (name, parent_id)
VALUES ('Công nghệ thông tin', NULL),
       ('Phần mềm', 1),
       ('Web Development', 1),
       ('Mobile Development', 1),
       ('Data Science', 1),
       ('AI/ML', 1),
       ('DevOps', 1),
       ('Cybersecurity', 1),
       ('Tài chính', NULL),
       ('Ngân hàng', 9),
       ('Bảo hiểm', 9);

-- Payment Method
INSERT INTO payment_method (name)
VALUES ('Chuyển khoản ngân hàng'),
       ('Ví điện tử'),
       ('Thẻ tín dụng'),
       ('Thẻ ghi nợ'),
       ('Tiền mặt'),
       ('PayPal'),
       ('Momo'),
       ('ZaloPay'),
       ('VNPay');

-- Payment Status
INSERT INTO payment_status (name)
VALUES ('Pending'),
       ('Processing'),
       ('Completed'),
       ('Failed'),
       ('Cancelled'),
       ('Refunded');

-- Report Status
INSERT INTO report_status (name)
VALUES ('Pending'),
       ('Under Review'),
       ('Resolved'),
       ('Rejected'),
       ('Closed');



-- Province (63 tỉnh thành Việt Nam)
INSERT INTO province (name)
VALUES ('Hà Nội'),
       ('Hồ Chí Minh'),
       ('Đà Nẵng'),
       ('Hải Phòng'),
       ('Cần Thơ'),
       ('An Giang'),
       ('Bà Rịa - Vũng Tàu'),
       ('Bắc Giang'),
       ('Bắc Kạn'),
       ('Bạc Liêu'),
       ('Bắc Ninh'),
       ('Bến Tre'),
       ('Bình Định'),
       ('Bình Dương'),
       ('Bình Phước'),
       ('Bình Thuận'),
       ('Cà Mau'),
       ('Cao Bằng'),
       ('Đắk Lắk'),
       ('Đắk Nông'),
       ('Điện Biên'),
       ('Đồng Nai'),
       ('Đồng Tháp'),
       ('Gia Lai'),
       ('Hà Giang'),
       ('Hà Nam'),
       ('Hà Tĩnh'),
       ('Hải Dương'),
       ('Hậu Giang'),
       ('Hòa Bình'),
       ('Hưng Yên'),
       ('Khánh Hòa'),
       ('Kiên Giang'),
       ('Kon Tum'),
       ('Lai Châu'),
       ('Lâm Đồng'),
       ('Lạng Sơn'),
       ('Lào Cai'),
       ('Long An'),
       ('Nam Định'),
       ('Nghệ An'),
       ('Ninh Bình'),
       ('Ninh Thuận'),
       ('Phú Thọ'),
       ('Phú Yên'),
       ('Quảng Bình'),
       ('Quảng Nam'),
       ('Quảng Ngãi'),
       ('Quảng Ninh'),
       ('Quảng Trị'),
       ('Sóc Trăng'),
       ('Sơn La'),
       ('Tây Ninh'),
       ('Thái Bình'),
       ('Thái Nguyên'),
       ('Thanh Hóa'),
       ('Thừa Thiên Huế'),
       ('Tiền Giang'),
       ('Trà Vinh'),
       ('Tuyên Quang'),
       ('Vĩnh Long'),
       ('Vĩnh Phúc'),
       ('Yên Bái');

-- Ward (Quận/Huyện/Phường/Xã của 63 tỉnh thành Việt Nam)
INSERT INTO ward (name, province_id)
VALUES
-- Hà Nội (1) - 30 quận/huyện
('Quận Ba Đình', 1),
('Quận Hoàn Kiếm', 1),
('Quận Tây Hồ', 1),
('Quận Long Biên', 1),
('Quận Cầu Giấy', 1),
('Quận Đống Đa', 1),
('Quận Hai Bà Trưng', 1),
('Quận Hoàng Mai', 1),
('Quận Thanh Xuân', 1),
('Quận Sóc Sơn', 1),
('Quận Đông Anh', 1),
('Quận Gia Lâm', 1),
('Quận Nam Từ Liêm', 1),
('Quận Bắc Từ Liêm', 1),
('Quận Mê Linh', 1),
('Quận Hà Đông', 1),
('Quận Sơn Tây', 1),
('Huyện Ba Vì', 1),
('Huyện Phúc Thọ', 1),
('Huyện Đan Phượng', 1),
('Huyện Hoài Đức', 1),
('Huyện Quốc Oai', 1),
('Huyện Thạch Thất', 1),
('Huyện Chương Mỹ', 1),
('Huyện Thanh Oai', 1),
('Huyện Thường Tín', 1),
('Huyện Phú Xuyên', 1),
('Huyện Ứng Hòa', 1),
('Huyện Mỹ Đức', 1),
('Huyện Thanh Trì', 1),
-- Hồ Chí Minh (2) - 24 quận/huyện
('Quận 1', 2),
('Quận 2', 2),
('Quận 3', 2),
('Quận 4', 2),
('Quận 5', 2),
('Quận 6', 2),
('Quận 7', 2),
('Quận 8', 2),
('Quận 9', 2),
('Quận 10', 2),
('Quận 11', 2),
('Quận 12', 2),
('Quận Bình Thạnh', 2),
('Quận Tân Bình', 2),
('Quận Tân Phú', 2),
('Quận Phú Nhuận', 2),
('Quận Thủ Đức', 2),
('Quận Gò Vấp', 2),
('Quận Bình Tân', 2),
('Huyện Củ Chi', 2),
('Huyện Hóc Môn', 2),
('Huyện Bình Chánh', 2),
('Huyện Nhà Bè', 2),
('Huyện Cần Giờ', 2),
-- Đà Nẵng (3) - 8 quận/huyện
('Quận Hải Châu', 3),
('Quận Thanh Khê', 3),
('Quận Sơn Trà', 3),
('Quận Ngũ Hành Sơn', 3),
('Quận Liên Chiểu', 3),
('Quận Cẩm Lệ', 3),
('Huyện Hòa Vang', 3),
('Huyện Hoàng Sa', 3),
-- Hải Phòng (4) - 15 quận/huyện
('Quận Hồng Bàng', 4),
('Quận Ngô Quyền', 4),
('Quận Lê Chân', 4),
('Quận Hải An', 4),
('Quận Kiến An', 4),
('Quận Đồ Sơn', 4),
('Quận Dương Kinh', 4),
('Huyện Thuỷ Nguyên', 4),
('Huyện An Dương', 4),
('Huyện An Lão', 4),
('Huyện Kiến Thuỵ', 4),
('Huyện Tiên Lãng', 4),
('Huyện Vĩnh Bảo', 4),
('Huyện Cát Hải', 4),
('Huyện Bạch Long Vĩ', 4),
-- Cần Thơ (5) - 9 quận/huyện
('Quận Ninh Kiều', 5),
('Quận Ô Môn', 5),
('Quận Bình Thuỷ', 5),
('Quận Cái Răng', 5),
('Quận Thốt Nốt', 5),
('Huyện Vĩnh Thạnh', 5),
('Huyện Cờ Đỏ', 5),
('Huyện Phong Điền', 5),
('Huyện Thới Lai', 5),
-- An Giang (6) - 11 huyện/thị xã
('Thành phố Long Xuyên', 6),
('Thành phố Châu Đốc', 6),
('Thị xã Tân Châu', 6),
('Huyện An Phú', 6),
('Huyện Châu Phú', 6),
('Huyện Châu Thành', 6),
('Huyện Chợ Mới', 6),
('Huyện Phú Tân', 6),
('Huyện Thoại Sơn', 6),
('Huyện Tri Tôn', 6),
('Huyện Tịnh Biên', 6),
-- Bà Rịa - Vũng Tàu (7) - 8 huyện/thị xã
('Thành phố Vũng Tàu', 7),
('Thành phố Bà Rịa', 7),
('Thị xã Phú Mỹ', 7),
('Huyện Châu Đức', 7),
('Huyện Côn Đảo', 7),
('Huyện Đất Đỏ', 7),
('Huyện Long Điền', 7),
('Huyện Tân Thành', 7),
('Huyện Xuyên Mộc', 7),
-- Bắc Giang (8) - 10 huyện/thị xã
('Thành phố Bắc Giang', 8),
('Huyện Yên Thế', 8),
('Huyện Tân Yên', 8),
('Huyện Lạng Giang', 8),
('Huyện Lục Nam', 8),
('Huyện Lục Ngạn', 8),
('Huyện Sơn Động', 8),
('Huyện Yên Dũng', 8),
('Huyện Việt Yên', 8),
('Huyện Hiệp Hòa', 8),
-- Bắc Kạn (9) - 8 huyện/thị xã
('Thành phố Bắc Kạn', 9),
('Huyện Pác Nặm', 9),
('Huyện Ba Bể', 9),
('Huyện Ngân Sơn', 9),
('Huyện Bạch Thông', 9),
('Huyện Chợ Đồn', 9),
('Huyện Chợ Mới', 9),
('Huyện Na Rì', 9),
-- Bạc Liêu (10) - 7 huyện/thị xã
('Thành phố Bạc Liêu', 10),
('Huyện Hồng Dân', 10),
('Huyện Phước Long', 10),
('Huyện Vĩnh Lợi', 10),
('Huyện Giá Rai', 10),
('Huyện Đông Hải', 10),
('Huyện Hoà Bình', 10),
-- Bắc Ninh (11) - 9 huyện/thị xã
('Thành phố Bắc Ninh', 11),
('Thị xã Yên Phong', 11),
('Huyện Quế Võ', 11),
('Huyện Tiên Du', 11),
('Huyện Từ Sơn', 11),
('Huyện Yên Phong', 11),
('Huyện Gia Bình', 11),
('Huyện Lương Tài', 11),
('Huyện Võ Giàng', 11),
-- Bến Tre (12) - 9 huyện/thị xã
('Thành phố Bến Tre', 12),
('Huyện Châu Thành', 12),
('Huyện Chợ Lách', 12),
('Huyện Mỏ Cày Bắc', 12),
('Huyện Mỏ Cày Nam', 12),
('Huyện Giồng Trôm', 12),
('Huyện Bình Đại', 12),
('Huyện Ba Tri', 12),
('Huyện Thạnh Phú', 12),
-- Bình Định (13) - 11 huyện/thị xã
('Thành phố Quy Nhon', 13),
('Thị xã An Nhơn', 13),
('Huyện Hoài Nhơn', 13),
('Huyện Hoài Ân', 13),
('Huyện Phù Mỹ', 13),
('Huyện Phù Cát', 13),
('Huyện Vĩnh Thạnh', 13),
('Huyện Tây Sơn', 13),
('Huyện Tuy Phước', 13),
('Huyện Vân Canh', 13),
('Huyện An Lão', 13),
-- Bình Dương (14) - 9 huyện/thị xã
('Thành phố Thủ Dầu Một', 14),
('Thị xã Dĩ An', 14),
('Thị xã Thuận An', 14),
('Thị xã Tân Uyên', 14),
('Huyện Bến Cát', 14),
('Huyện Dầu Tiếng', 14),
('Huyện Bàu Bàng', 14),
('Huyện Phú Giáo', 14),
('Huyện Bắc Tân Uyên', 14),
-- Bình Phước (15) - 11 huyện/thị xã
('Thành phố Đồng Xoài', 15),
('Thị xã Bình Long', 15),
('Huyện Bù Đăng', 15),
('Huyện Bù Gia Mập', 15),
('Huyện Bù Đốp', 15),
('Huyện Chơn Thành', 15),
('Huyện Đồng Phú', 15),
('Huyện Hớn Quản', 15),
('Huyện Lộc Ninh', 15),
('Huyện Bù Nho', 15),
('Huyện Phú Riềng', 15),
-- Bình Thuận (16) - 10 huyện/thị xã
('Thành phố Phan Thiết', 16),
('Thị xã La Gi', 16),
('Huyện Tuy Phong', 16),
('Huyện Bắc Bình', 16),
('Huyện Hàm Thuận Bắc', 16),
('Huyện Hàm Thuận Nam', 16),
('Huyện Tánh Linh', 16),
('Huyện Đức Linh', 16),
('Huyện Hàm Tân', 16),
('Huyện Phú Quí', 16),
-- Cà Mau (17) - 9 huyện/thị xã
('Thành phố Cà Mau', 17),
('Huyện U Minh', 17),
('Huyện Thới Bình', 17),
('Huyện Trần Văn Thời', 17),
('Huyện Cái Nước', 17),
('Huyện Đầm Dơi', 17),
('Huyện Năm Căn', 17),
('Huyện Phú Tân', 17),
('Huyện Ngọc Hiển', 17),
-- Cao Bằng (18) - 13 huyện/thị xã
('Thành phố Cao Bằng', 18),
('Huyện Bảo Lâm', 18),
('Huyện Bảo Lạc', 18),
('Huyện Hà Quảng', 18),
('Huyện Trùng Khánh', 18),
('Huyện Hạ Lang', 18),
('Huyện Quảng Uyên', 18),
('Huyện Phục Hoà', 18),
('Huyện Hoà An', 18),
('Huyện Nguyên Bình', 18),
('Huyện Thạch An', 18),
('Huyện Bạch Thông', 18),
('Huyện Thông Nông', 18),
-- Đắk Lắk (19) - 15 huyện/thị xã
('Thành phố Buôn Ma Thuột', 19),
('Thị xã Buôn Hồ', 19),
('Huyện Ea H''leo', 19),
('Huyện Ea Súp', 19),
('Huyện Buôn Đôn', 19),
('Huyện Cư M''gar', 19),
('Huyện Krông Búk', 19),
('Huyện Krông Năng', 19),
('Huyện Ea Kar', 19),
('Huyện M''Đrắk', 19),
('Huyện Krông Bông', 19),
('Huyện Krông Pắk', 19),
('Huyện Krông A Na', 19),
('Huyện Lắk', 19),
('Huyện Cư Kuin', 19),
-- Đắk Nông (20) - 8 huyện/thị xã
('Thành phố Gia Nghĩa', 20),
('Huyện Đăk Glong', 20),
('Huyện Cư Jút', 20),
('Huyện Đắk Mil', 20),
('Huyện Krông Nô', 20),
('Huyện Đắk Song', 20),
('Huyện Đắk R''Lấp', 20),
('Huyện Tuy Đức', 20),
-- Điện Biên (21) - 10 huyện/thị xã
('Thành phố Điện Biên Phủ', 21),
('Thị xã Mường Lay', 21),
('Huyện Mường Nhé', 21),
('Huyện Mường Chà', 21),
('Huyện Tủa Chùa', 21),
('Huyện Tuần Giáo', 21),
('Huyện Điện Biên', 21),
('Huyện Điện Biên Đông', 21),
('Huyện Mường Ảng', 21),
('Huyện Nậm Pồ', 21),
-- Đồng Nai (22) - 11 huyện/thị xã
('Thành phố Biên Hòa', 22),
('Thành phố Long Khánh', 22),
('Thị xã Tân Phú', 22),
('Huyện Vĩnh Cửu', 22),
('Huyện Định Quán', 22),
('Huyện Thống Nhất', 22),
('Huyện Cẩm Mỹ', 22),
('Huyện Long Thành', 22),
('Huyện Xuân Lộc', 22),
('Huyện Nhơn Trạch', 22),
('Huyện Trảng Bom', 22),
-- Đồng Tháp (23) - 12 huyện/thị xã
('Thành phố Cao Lãnh', 23),
('Thành phố Sa Đéc', 23),
('Thị xã Hồng Ngự', 23),
('Huyện Tân Hồng', 23),
('Huyện Hồng Ngự', 23),
('Huyện Tam Nông', 23),
('Huyện Tân Hưng', 23),
('Huyện Lấp Vò', 23),
('Huyện Lai Vung', 23),
('Huyện Châu Thành', 23),
('Huyện Thanh Bình', 23),
('Huyện Tháp Mười', 23),
-- Gia Lai (24) - 17 huyện/thị xã
('Thành phố Pleiku', 24),
('Thị xã An Khê', 24),
('Thị xã Ayun Pa', 24),
('Huyện KBang', 24),
('Huyện Đăk Đoa', 24),
('Huyện Chư Păh', 24),
('Huyện Ia Grai', 24),
('Huyện Mang Yang', 24),
('Huyện Kông Chro', 24),
('Huyện Đức Cơ', 24),
('Huyện Chư Prông', 24),
('Huyện Chư Sê', 24),
('Huyện Đăk Pơ', 24),
('Huyện Ia Pa', 24),
('Huyện Krông Pa', 24),
('Huyện Phú Thiện', 24),
('Huyện Chư Pưh', 24),
-- Hà Giang (25) - 11 huyện/thị xã
('Thành phố Hà Giang', 25),
('Huyện Đồng Văn', 25),
('Huyện Mèo Vạc', 25),
('Huyện Yên Minh', 25),
('Huyện Quản Bạ', 25),
('Huyện Quang Bình', 25),
('Huyện Xín Mần', 25),
('Huyện Bắc Quang', 25),
('Huyện Quang Bình', 25),
('Huyện Hoàng Su Phì', 25),
('Huyện Vị Xuyên', 25),
-- Hà Nam (26) - 6 huyện/thị xã
('Thành phố Phủ Lý', 26),
('Thị xã Duy Tiên', 26),
('Huyện Kim Bảng', 26),
('Huyện Thanh Liêm', 26),
('Huyện Bình Lục', 26),
('Huyện Lý Nhân', 26),
-- Hà Tĩnh (27) - 13 huyện/thị xã
('Thành phố Hà Tĩnh', 27),
('Thị xã Hồng Lĩnh', 27),
('Huyện Hương Sơn', 27),
('Huyện Đức Thọ', 27),
('Huyện Vũ Quang', 27),
('Huyện Nghi Xuân', 27),
('Huyện Can Lộc', 27),
('Huyện Hương Khê', 27),
('Huyện Thạch Hà', 27),
('Huyện Cẩm Xuyên', 27),
('Huyện Kỳ Anh', 27),
('Huyện Lộc Hà', 27),
-- Hải Dương (28) - 12 huyện/thị xã
('Thành phố Hải Dương', 28),
('Thị xã Chí Linh', 28),
('Huyện Nam Sách', 28),
('Huyện Kinh Môn', 28),
('Huyện Kim Thành', 28),
('Huyện Thanh Hà', 28),
('Huyện Cẩm Giàng', 28),
('Huyện Bình Giang', 28),
('Huyện Gia Lộc', 28),
('Huyện Tứ Kỳ', 28),
('Huyện Ninh Giang', 28),
('Huyện Thanh Miện', 28),
-- Hậu Giang (29) - 8 huyện/thị xã
('Thành phố Vị Thanh', 29),
('Thị xã Ngã Bảy', 29),
('Huyện Châu Thành', 29),
('Huyện Châu Thành A', 29),
('Huyện Phụng Hiệp', 29),
('Huyện Vị Thủy', 29),
('Huyện Long Mỹ', 29),
('Thị xã Long Mỹ', 29),
-- Hòa Bình (30) - 10 huyện/thị xã
('Thành phố Hòa Bình', 30),
('Huyện Đà Bắc', 30),
('Huyện Lương Sơn', 30),
('Huyện Kim Bôi', 30),
('Huyện Cao Phong', 30),
('Huyện Tân Lạc', 30),
('Huyện Mai Châu', 30),
('Huyện Lạc Sơn', 30),
('Huyện Yên Thủy', 30),
('Huyện Lạc Thủy', 30),
-- Hưng Yên (31) - 10 huyện/thị xã
('Thành phố Hưng Yên', 31),
('Thị xã Mỹ Hào', 31),
('Huyện Văn Lâm', 31),
('Huyện Văn Giang', 31),
('Huyện Yên Mỹ', 31),
('Huyện Mỹ Hào', 31),
('Huyện Ân Thi', 31),
('Huyện Khoái Châu', 31),
('Huyện Kim Động', 31),
('Huyện Tiên Lữ', 31),
-- Khánh Hòa (32) - 9 huyện/thị xã
('Thành phố Nha Trang', 32),
('Thành phố Cam Ranh', 32),
('Thị xã Ninh Hòa', 32),
('Huyện Vạn Ninh', 32),
('Huyện Khánh Vĩnh', 32),
('Huyện Diên Khánh', 32),
('Huyện Khánh Sơn', 32),
('Huyện Trường Sa', 32),
('Huyện Cam Lâm', 32),
-- Kiên Giang (33) - 15 huyện/thị xã
('Thành phố Rạch Giá', 33),
('Thành phố Hà Tiên', 33),
('Thị xã Kiên Lương', 33),
('Huyện Hòn Đất', 33),
('Huyện Tân Hiệp', 33),
('Huyện Châu Thành', 33),
('Huyện Giồng Riềng', 33),
('Huyện Gò Quao', 33),
('Huyện An Biên', 33),
('Huyện An Minh', 33),
('Huyện Vĩnh Thuận', 33),
('Huyện Phú Quốc', 33),
('Huyện Kiên Hải', 33),
('Huyện U Minh Thượng', 33),
('Huyện Giang Thành', 33),
-- Kon Tum (34) - 10 huyện/thị xã
('Thành phố Kon Tum', 34),
('Huyện Đắk Glei', 34),
('Huyện Ngọc Hồi', 34),
('Huyện Đắk Tô', 34),
('Huyện Kon Plông', 34),
('Huyện Kon Rẫy', 34),
('Huyện Đắk Hà', 34),
('Huyện Sa Thầy', 34),
('Huyện Tu Mơ Rông', 34),
('Huyện Ia H''Drai', 34),
-- Lai Châu (35) - 8 huyện/thị xã
('Thành phố Lai Châu', 35),
('Huyện Tam Đường', 35),
('Huyện Mường Tè', 35),
('Huyện Sìn Hồ', 35),
('Huyện Phong Thổ', 35),
('Huyện Than Uyên', 35),
('Huyện Tân Uyên', 35),
('Huyện Nậm Nhùn', 35),
-- Lâm Đồng (36) - 12 huyện/thị xã
('Thành phố Đà Lạt', 36),
('Thành phố Bảo Lộc', 36),
('Thị xã Đức Trọng', 36),
('Huyện Lạc Dương', 36),
('Huyện Đơn Dương', 36),
('Huyện Đức Trọng', 36),
('Huyện Lâm Hà', 36),
('Huyện Bảo Lâm', 36),
('Huyện Đạ Huoai', 36),
('Huyện Đạ Tẻh', 36),
('Huyện Cát Tiên', 36),
('Huyện Đam Rông', 36),
-- Lạng Sơn (37) - 11 huyện/thị xã
('Thành phố Lạng Sơn', 37),
('Huyện Tràng Định', 37),
('Huyện Bình Gia', 37),
('Huyện Văn Lãng', 37),
('Huyện Cao Lộc', 37),
('Huyện Văn Quan', 37),
('Huyện Bắc Sơn', 37),
('Huyện Hữu Lũng', 37),
('Huyện Chi Lăng', 37),
('Huyện Lộc Bình', 37),
('Huyện Đình Lập', 37),
-- Lào Cai (38) - 9 huyện/thị xã
('Thành phố Lào Cai', 38),
('Thị xã Sa Pa', 38),
('Huyện Bát Xát', 38),
('Huyện Mường Khương', 38),
('Huyện Si Ma Cai', 38),
('Huyện Bảo Thắng', 38),
('Huyện Bảo Yên', 38),
('Huyện Sa Pa', 38),
('Huyện Văn Bàn', 38),
-- Long An (39) - 15 huyện/thị xã
('Thành phố Tân An', 39),
('Thị xã Kiến Tường', 39),
('Huyện Tân Hưng', 39),
('Huyện Vĩnh Hưng', 39),
('Huyện Mộc Hóa', 39),
('Huyện Tân Thạnh', 39),
('Huyện Thạnh Hóa', 39),
('Huyện Đức Huệ', 39),
('Huyện Đức Hòa', 39),
('Huyện Bến Lức', 39),
('Huyện Thủ Thừa', 39),
('Huyện Tân Trụ', 39),
('Huyện Cần Đước', 39),
('Huyện Cần Giuộc', 39),
('Huyện Châu Thành', 39),
-- Nam Định (40) - 10 huyện/thị xã
('Thành phố Nam Định', 40),
('Huyện Mỹ Lộc', 40),
('Huyện Vụ Bản', 40),
('Huyện Ý Yên', 40),
('Huyện Nghĩa Hưng', 40),
('Huyện Nam Trực', 40),
('Huyện Trực Ninh', 40),
('Huyện Xuân Trường', 40),
('Huyện Giao Thủy', 40),
('Huyện Hải Hậu', 40),
-- Nghệ An (41) - 21 huyện/thị xã
('Thành phố Vinh', 41),
('Thị xã Cửa Lò', 41),
('Thị xã Thái Hòa', 41),
('Huyện Quế Phong', 41),
('Huyện Quỳ Châu', 41),
('Huyện Kỳ Sơn', 41),
('Huyện Tương Dương', 41),
('Huyện Nghĩa Đàn', 41),
('Huyện Quỳ Hợp', 41),
('Huyện Quỳnh Lưu', 41),
('Huyện Con Cuông', 41),
('Huyện Tân Kỳ', 41),
('Huyện Anh Sơn', 41),
('Huyện Diễn Châu', 41),
('Huyện Yên Thành', 41),
('Huyện Đô Lương', 41),
('Huyện Thanh Chương', 41),
('Huyện Nghi Lộc', 41),
('Huyện Nam Đàn', 41),
('Huyện Hưng Nguyên', 41),
('Huyện Nghi Xuân', 41),
-- Ninh Bình (42) - 8 huyện/thị xã
('Thành phố Ninh Bình', 42),
('Thành phố Tam Điệp', 42),
('Huyện Nho Quan', 42),
('Huyện Gia Viễn', 42),
('Huyện Hoa Lư', 42),
('Huyện Yên Khánh', 42),
('Huyện Kim Sơn', 42),
('Huyện Yên Mô', 42),
-- Ninh Thuận (43) - 7 huyện/thị xã
('Thành phố Phan Rang - Tháp Chàm', 43),
('Huyện Bác Ái', 43),
('Huyện Ninh Sơn', 43),
('Huyện Ninh Hải', 43),
('Huyện Ninh Phước', 43),
('Huyện Thuận Bắc', 43),
('Huyện Thuận Nam', 43),
-- Phú Thọ (44) - 13 huyện/thị xã
('Thành phố Việt Trì', 44),
('Thị xã Phú Thọ', 44),
('Huyện Đoan Hùng', 44),
('Huyện Hạ Hòa', 44),
('Huyện Thanh Ba', 44),
('Huyện Phù Ninh', 44),
('Huyện Yên Lập', 44),
('Huyện Cẩm Khê', 44),
('Huyện Tam Nông', 44),
('Huyện Lâm Thao', 44),
('Huyện Thanh Sơn', 44),
('Huyện Thanh Thủy', 44),
('Huyện Tân Sơn', 44),
-- Phú Yên (45) - 9 huyện/thị xã
('Thành phố Tuy Hòa', 45),
('Thị xã Sông Cầu', 45),
('Huyện Đồng Xuân', 45),
('Huyện Tuy An', 45),
('Huyện Sơn Hòa', 45),
('Huyện Sông Hinh', 45),
('Huyện Tây Hòa', 45),
('Huyện Phú Hòa', 45),
('Huyện Đông Hòa', 45),
-- Quảng Bình (46) - 8 huyện/thị xã
('Thành phố Đồng Hới', 46),
('Thị xã Ba Đồn', 46),
('Huyện Minh Hóa', 46),
('Huyện Tuyên Hóa', 46),
('Huyện Quảng Trạch', 46),
('Huyện Bố Trạch', 46),
('Huyện Quảng Ninh', 46),
('Huyện Lệ Thủy', 46),
-- Quảng Nam (47) - 18 huyện/thị xã
('Thành phố Tam Kỳ', 47),
('Thành phố Hội An', 47),
('Thị xã Điện Bàn', 47),
('Huyện Duy Xuyên', 47),
('Huyện Đại Lộc', 47),
('Huyện Đông Giang', 47),
('Huyện Hiệp Đức', 47),
('Huyện Nam Giang', 47),
('Huyện Phước Sơn', 47),
('Huyện Tây Giang', 47),
('Huyện Phú Ninh', 47),
('Huyện Núi Thành', 47),
('Huyện Tiên Phước', 47),
('Huyện Bắc Trà My', 47),
('Huyện Nam Trà My', 47),
('Huyện Thăng Bình', 47),
-- Quảng Ngãi (48) - 14 huyện/thị xã
('Thành phố Quảng Ngãi', 48),
('Huyện Bình Sơn', 48),
('Huyện Trà Bồng', 48),
('Huyện Tây Trà', 48),
('Huyện Sơn Tịnh', 48),
('Huyện Tư Nghĩa', 48),
('Huyện Sơn Hà', 48),
('Huyện Sơn Tây', 48),
('Huyện Minh Long', 48),
('Huyện Nghĩa Hành', 48),
('Huyện Mộ Đức', 48),
('Huyện Đức Phổ', 48),
('Huyện Ba Tơ', 48),
('Huyện Lý Sơn', 48),
-- Quảng Ninh (49) - 13 huyện/thị xã
('Thành phố Hạ Long', 49),
('Thành phố Móng Cái', 49),
('Thành phố Cẩm Phả', 49),
('Thành phố Uông Bí', 49),
('Thị xã Bình Liêu', 49),
('Huyện Tiên Yên', 49),
('Huyện Đầm Hà', 49),
('Huyện Hải Hà', 49),
('Huyện Ba Chẽ', 49),
('Huyện Vân Đồn', 49),
('Huyện Hoành Bồ', 49),
('Huyện Cô Tô', 49),
('Huyện Đông Triều', 49),
-- Quảng Trị (50) - 10 huyện/thị xã
('Thành phố Đông Hà', 50),
('Thị xã Quảng Trị', 50),
('Huyện Vĩnh Linh', 50),
('Huyện Hướng Hóa', 50),
('Huyện Gio Linh', 50),
('Huyện Đa Krông', 50),
('Huyện Cam Lộ', 50),
('Huyện Triệu Phong', 50),
('Huyện Hải Lăng', 50),
('Huyện Cồn Cỏ', 50),
-- Sóc Trăng (51) - 11 huyện/thị xã
('Thành phố Sóc Trăng', 51),
('Huyện Châu Thành', 51),
('Huyện Kế Sách', 51),
('Huyện Mỹ Tú', 51),
('Huyện Cù Lao Dung', 51),
('Huyện Long Phú', 51),
('Huyện Mỹ Xuyên', 51),
('Huyện Ngã Năm', 51),
('Huyện Thạnh Trị', 51),
('Huyện Vĩnh Châu', 51),
('Huyện Trần Đề', 51),
-- Sơn La (52) - 12 huyện/thị xã
('Thành phố Sơn La', 52),
('Huyện Quỳnh Nhai', 52),
('Huyện Mường La', 52),
('Huyện Thuận Châu', 52),
('Huyện Mường Sơn', 52),
('Huyện Sông Mã', 52),
('Huyện Sốp Cộp', 52),
('Huyện Yên Châu', 52),
('Huyện Mai Sơn', 52),
('Huyện Mộc Châu', 52),
('Huyện Mường Khương', 52),
('Huyện Vân Hồ', 52),
-- Tây Ninh (53) - 9 huyện/thị xã
('Thành phố Tây Ninh', 53),
('Huyện Tân Biên', 53),
('Huyện Tân Châu', 53),
('Huyện Dương Minh Châu', 53),
('Huyện Châu Thành', 53),
('Huyện Hòa Thành', 53),
('Huyện Gò Dầu', 53),
('Huyện Bến Cầu', 53),
('Huyện Trảng Bàng', 53),
-- Thái Bình (54) - 8 huyện/thị xã
('Thành phố Thái Bình', 54),
('Huyện Quỳnh Phụ', 54),
('Huyện Hưng Hà', 54),
('Huyện Đông Hưng', 54),
('Huyện Thái Thụy', 54),
('Huyện Tiền Hải', 54),
('Huyện Kiến Xương', 54),
('Huyện Vũ Thư', 54),
-- Thái Nguyên (55) - 9 huyện/thị xã
('Thành phố Thái Nguyên', 55),
('Thành phố Sông Công', 55),
('Thị xã Phổ Yên', 55),
('Huyện Định Hóa', 55),
('Huyện Phú Lương', 55),
('Huyện Đồng Hỷ', 55),
('Huyện Võ Nhai', 55),
('Huyện Đại Từ', 55),
('Huyện Phú Bình', 55),
-- Thanh Hóa (56) - 27 huyện/thị xã
('Thành phố Thanh Hóa', 56),
('Thị xã Bỉm Sơn', 56),
('Thị xã Sầm Sơn', 56),
('Huyện Mường Lát', 56),
('Huyện Quan Hóa', 56),
('Huyện Bá Thước', 56),
('Huyện Quan Sơn', 56),
('Huyện Lang Chánh', 56),
('Huyện Ngọc Lặc', 56),
('Huyện Cẩm Thủy', 56),
('Huyện Thạch Thành', 56),
('Huyện Hà Trung', 56),
('Huyện Vĩnh Lộc', 56),
('Huyện Yên Định', 56),
('Huyện Thọ Xuân', 56),
('Huyện Thường Xuân', 56),
('Huyện Triệu Sơn', 56),
('Huyện Thiệu Hóa', 56),
('Huyện Hoằng Hóa', 56),
('Huyện Hậu Lộc', 56),
('Huyện Nga Sơn', 56),
('Huyện Như Xuân', 56),
('Huyện Như Thanh', 56),
('Huyện Nông Cống', 56),
('Huyện Đông Sơn', 56),
('Huyện Quảng Xương', 56),
('Huyện Tĩnh Gia', 56),
-- Thừa Thiên Huế (57) - 9 huyện/thị xã
('Thành phố Huế', 57),
('Thị xã Hương Thủy', 57),
('Thị xã Hương Trà', 57),
('Huyện Phong Điền', 57),
('Huyện Quảng Điền', 57),
('Huyện Phú Vang', 57),
('Huyện Phú Lộc', 57),
('Huyện A Lưới', 57),
('Huyện Nam Đông', 57),
-- Tiền Giang (58) - 11 huyện/thị xã
('Thành phố Mỹ Tho', 58),
('Thị xã Gò Công', 58),
('Thị xã Cai Lậy', 58),
('Huyện Tân Phú Đông', 58),
('Huyện Cái Bè', 58),
('Huyện Cai Lậy', 58),
('Huyện Châu Thành', 58),
('Huyện Chợ Gạo', 58),
('Huyện Gò Công Tây', 58),
('Huyện Gò Công Đông', 58),
('Huyện Tân Phước', 58),
-- Trà Vinh (59) - 9 huyện/thị xã
('Thành phố Trà Vinh', 59),
('Huyện Càng Long', 59),
('Huyện Cầu Kè', 59),
('Huyện Tiểu Cần', 59),
('Huyện Châu Thành', 59),
('Huyện Cầu Ngang', 59),
('Huyện Trà Cú', 59),
('Huyện Duyên Hải', 59),
('Thị xã Duyên Hải', 59),
-- Tuyên Quang (60) - 7 huyện/thị xã
('Thành phố Tuyên Quang', 60),
('Huyện Lâm Bình', 60),
('Huyện Na Hang', 60),
('Huyện Chiêm Hóa', 60),
('Huyện Hàm Yên', 60),
('Huyện Yên Sơn', 60),
('Huyện Sơn Dương', 60),
-- Vĩnh Long (61) - 8 huyện/thị xã
('Thành phố Vĩnh Long', 61),
('Huyện Long Hồ', 61),
('Huyện Mang Thít', 61),
('Huyện Vũng Liêm', 61),
('Huyện Tam Bình', 61),
('Huyện Bình Minh', 61),
('Huyện Trà Ôn', 61),
('Huyện Bình Tân', 61),
-- Vĩnh Phúc (62) - 9 huyện/thị xã
('Thành phố Vĩnh Yên', 62),
('Thị xã Phúc Yên', 62),
('Huyện Lập Thạch', 62),
('Huyện Tam Dương', 62),
('Huyện Tam Đảo', 62),
('Huyện Bình Xuyên', 62),
('Huyện Yên Lạc', 62),
('Huyện Vĩnh Tường', 62),
('Huyện Sông Lô', 62),
-- Yên Bái (63) - 9 huyện/thị xã
('Thành phố Yên Bái', 63),
('Thị xã Nghĩa Lộ', 63),
('Huyện Lục Yên', 63),
('Huyện Văn Yên', 63),
('Huyện Mù Cang Chải', 63),
('Huyện Trấn Yên', 63),
('Huyện Trạm Tấu', 63),
('Huyện Văn Chấn', 63),
('Huyện Yên Bình', 63);
-- ============================================
-- MAIN ENTITIES
-- ============================================

-- Company
INSERT INTO company (id, name, description, address, website, company_size_id, logo)
VALUES ('650e8400-e29b-41d4-a716-446655440001', 'FPT Software', 'Công ty phần mềm hàng đầu Việt Nam',
        'Hà Nội, Việt Nam', 'https://www.fpt-software.com', 6, 'https://example.com/logo/fpt.png'),
       ('650e8400-e29b-41d4-a716-446655440002', 'Viettel Solutions', 'Giải pháp công nghệ thông tin',
        'Hà Nội, Việt Nam', 'https://www.viettel-solutions.com', 6, 'https://example.com/logo/viettel.png'),
       ('650e8400-e29b-41d4-a716-446655440003', 'TMA Solutions', 'Công ty phần mềm quốc tế', 'Hồ Chí Minh, Việt Nam',
        'https://www.tmasolutions.com', 5, 'https://example.com/logo/tma.png'),
       ('650e8400-e29b-41d4-a716-446655440004', 'CMC Corporation', 'Tập đoàn công nghệ thông tin', 'Hà Nội, Việt Nam',
        'https://www.cmc.com.vn', 6, 'https://example.com/logo/cmc.png'),
       ('650e8400-e29b-41d4-a716-446655440005', 'VNG Corporation', 'Công ty công nghệ và giải trí',
        'Hồ Chí Minh, Việt Nam', 'https://www.vng.com.vn', 5, 'https://example.com/logo/vng.png'),
       ('650e8400-e29b-41d4-a716-446655440006', 'Tech Startup XYZ', 'Startup công nghệ trẻ', 'Đà Nẵng, Việt Nam',
        'https://www.techstartup.xyz', 2, 'https://example.com/logo/startup.png');

-- User
-- Lưu ý: Password mặc định cho tất cả user là "123456"
INSERT INTO user (id, email, password, first_name, last_name, role_id, avatar, phone, gender, education, address,
                  website_link, birth_date, is_find_job, company_id, group_soft_skill)
VALUES
-- Admin
('750e8400-e29b-41d4-a716-446655440001', 'admin@gmail.com',
 '$2a$12$OKXQyj2v95r2eP5JVWa.kOEyS.OdeDhC.mn4qS990Ix6/Wntd.KIu', 'Admin', 'System',
 '550e8400-e29b-41d4-a716-446655440001', NULL, '0123456789', 'Male', 'Đại học', 'Hà Nội', 'https://admin.itjob.com',
 '1990-01-01', 0, NULL, 'Leadership, Communication'),
-- HR Users (thuộc công ty FPT và Viettel)
('750e8400-e29b-41d4-a716-446655440002', 'hr@gmail.com', '$2a$12$OKXQyj2v95r2eP5JVWa.kOEyS.OdeDhC.mn4qS990Ix6/Wntd.KIu',
 'Nguyễn', 'Văn A', '550e8400-e29b-41d4-a716-446655440002', NULL, '0987654321', 'Male', 'Đại học', 'Hà Nội', NULL,
 '1985-05-15', 0, '650e8400-e29b-41d4-a716-446655440001', 'Recruitment, Communication'),
('750e8400-e29b-41d4-a716-446655440003', 'hr2@gmail.com',
 '$2a$12$OKXQyj2v95r2eP5JVWa.kOEyS.OdeDhC.mn4qS990Ix6/Wntd.KIu', 'Trần', 'Thị B',
 '550e8400-e29b-41d4-a716-446655440002', NULL, '0912345678', 'Female', 'Đại học', 'Hà Nội', NULL, '1988-08-20', 0,
 '650e8400-e29b-41d4-a716-446655440002', 'HR Management');



-- Job
INSERT INTO job (job_position, company_id, detail_address, description_job, requirement, benefits, province_id,
                 industry_id, job_level_id, degree_level_id, employment_type_id, experience_id)
VALUES ('Java Developer', '650e8400-e29b-41d4-a716-446655440001', 'Tòa nhà FPT, Hà Nội',
        'Tìm kiếm Java Developer có kinh nghiệm phát triển ứng dụng web và mobile',
        'Kinh nghiệm 2-3 năm với Java, Spring Boot, MySQL', 'Lương cạnh tranh, bảo hiểm đầy đủ, đào tạo', 1, 2, 4, 4, 1,
        4),
       ('React Frontend Developer', '650e8400-e29b-41d4-a716-446655440002', 'Tòa nhà Viettel, Hà Nội',
        'Tuyển Frontend Developer chuyên về React và TypeScript', 'Thành thạo React, Redux, TypeScript, có portfolio',
        'Lương 15-25 triệu, làm việc linh hoạt', 1, 2, 3, 4, 1, 3),
       ('Full-stack Developer', '650e8400-e29b-41d4-a716-446655440003', 'Quận 1, Hồ Chí Minh',
        'Tuyển Full-stack Developer cho dự án startup', 'Node.js, React, MongoDB, có kinh nghiệm startup',
        'Equity, remote work, flexible hours', 2, 2, 4, 4, 6, 4),
       ('DevOps Engineer', '650e8400-e29b-41d4-a716-446655440004', 'Cầu Giấy, Hà Nội',
        'Tuyển DevOps Engineer quản lý infrastructure', 'Docker, Kubernetes, AWS, CI/CD',
        'Lương cao, môi trường chuyên nghiệp', 1, 1, 5, 4, 1, 5),
       ('Data Scientist', '650e8400-e29b-41d4-a716-446655440005', 'Quận 7, Hồ Chí Minh',
        'Tuyển Data Scientist cho dự án AI', 'Python, Machine Learning, TensorFlow, PhD preferred',
        'Lương rất cao, research opportunities', 2, 8, 5, 5, 1, 6),
       ('Mobile Developer (Flutter)', '650e8400-e29b-41d4-a716-446655440006', 'Đà Nẵng',
        'Tuyển Mobile Developer phát triển app Flutter', 'Flutter, Dart, có app trên store',
        'Startup environment, equity', 3, 11, 3, 4, 1, 3);

-- ============================================
-- USER PROFILE TABLES (Dữ liệu mẫu cho Admin và HR)
-- ============================================

-- Language Skill cho Admin và HR
INSERT INTO language_skill (language_id, level_language_id, user_id)
VALUES (1, 6, '750e8400-e29b-41d4-a716-446655440001'), -- Admin: Tiếng Việt - Bản ngữ
       (2, 5, '750e8400-e29b-41d4-a716-446655440001'), -- Admin: Tiếng Anh - Thành thạo
       (1, 6, '750e8400-e29b-41d4-a716-446655440002'), -- HR1: Tiếng Việt - Bản ngữ
       (2, 4, '750e8400-e29b-41d4-a716-446655440002'), -- HR1: Tiếng Anh - Tốt
       (1, 6, '750e8400-e29b-41d4-a716-446655440003'), -- HR2: Tiếng Việt - Bản ngữ
       (2, 3, '750e8400-e29b-41d4-a716-446655440003'); -- HR2: Tiếng Anh - Khá

-- ============================================
-- CONTENT TABLES
-- ============================================

-- Blog
INSERT INTO blog (title, picture, short_description, description, is_high_light, updated_person)
VALUES ('10 Kỹ năng cần thiết cho Developer năm 2024', '', 'Tổng hợp các kỹ năng quan trọng nhất',
        'Nội dung chi tiết về các kỹ năng...', 0, '750e8400-e29b-41d4-a716-446655440001'),
       ('Hướng dẫn viết CV IT hiệu quả', '', 'Cách viết CV thu hút nhà tuyển dụng', 'Chi tiết cách viết CV...', 0,
        '750e8400-e29b-41d4-a716-446655440001'),
       ('Xu hướng công nghệ 2024', '', 'Các xu hướng công nghệ nổi bật', 'Phân tích các xu hướng...', 0,
        '750e8400-e29b-41d4-a716-446655440001');

-- Review (HR đánh giá công ty khác)
INSERT INTO review (title, description, company_id, rated, user_id)
VALUES ('Môi trường làm việc tốt', 'Công ty có môi trường làm việc chuyên nghiệp, đồng nghiệp thân thiện',
        '650e8400-e29b-41d4-a716-446655440003', 5, '750e8400-e29b-41d4-a716-446655440002'),
       ('Lương và phúc lợi tốt', 'Lương cạnh tranh, có nhiều phúc lợi cho nhân viên',
        '650e8400-e29b-41d4-a716-446655440004', 4, '750e8400-e29b-41d4-a716-446655440003');

-- Report (Admin báo cáo job vi phạm)
INSERT INTO report (title, description, image_url, status_id, created_report, reported_user, reported_job)
VALUES ('Báo cáo vi phạm nội dung', 'Job posting có nội dung không phù hợp', 'https://example.com/report/1.jpg', 1,
        '750e8400-e29b-41d4-a716-446655440001', NULL, 1),
       ('Báo cáo spam', 'Job posting spam', NULL, 2, '750e8400-e29b-41d4-a716-446655440001', NULL, 2);

-- ============================================
-- PAYMENT TABLES
-- ============================================

-- Service Product (HR mua dịch vụ đăng tin)
INSERT INTO service_product (name, description, price, images, user_id, job_id)
VALUES ('Premium Job Posting', 'Đăng tin tuyển dụng nổi bật trong 30 ngày', 500000,
        'https://example.com/service/premium.jpg', '750e8400-e29b-41d4-a716-446655440002', 1),
       ('Featured Job', 'Tin tuyển dụng được ưu tiên hiển thị', 300000, 'https://example.com/service/featured.jpg',
        '750e8400-e29b-41d4-a716-446655440002', 2),
       ('Company Profile Premium', 'Nâng cấp hồ sơ công ty', 1000000, 'https://example.com/service/company.jpg',
        '750e8400-e29b-41d4-a716-446655440003', NULL);

-- Payment (HR thanh toán dịch vụ)
INSERT INTO payment (title, description, payment_method_id, status, service_product_id, user_id)
VALUES ('Thanh toán Premium Job Posting', 'Thanh toán cho dịch vụ đăng tin nổi bật', 1, 3, 1,
        '750e8400-e29b-41d4-a716-446655440002'),
       ('Thanh toán Featured Job', 'Thanh toán cho dịch vụ tin ưu tiên', 3, 3, 2,
        '750e8400-e29b-41d4-a716-446655440002'),
       ('Thanh toán Company Profile', 'Thanh toán nâng cấp hồ sơ công ty', 1, 1, 3,
        '750e8400-e29b-41d4-a716-446655440003');
